name = "Compost"
license = "MIT"
licenselink =  "https://github.com/canstand/compost/blob/master/LICENSE"
description = "A simple, lightweight theme for Hugo built with Tailwind CSS."

homepage = "https://github.com/canstand/compost/"
demosite = "https://canstand.github.io/compost/"

tags = ["blog", "minimal", "responsive", "dark mode", "dark", "light", "tailwind", "personal"]
features = ["improve Chinese style ", "syntax higlighting", "dark mode", "emoji"]

[author]
  name = "Can Stand"
  homepage = "https://kompost.cn/"

[original]
  author = "James Panther"
  homepage = "https://jamespanther.com/"
  repo = "https://github.com/jpanther/congo"