# Site configuration for the Compost demo site
# --------------------------------------------------------------------------
# IMPORTANT: You should not use this file as a template for configuration
# as it does not contain all the required theme settings!
# --------------------------------------------------------------------------

theme = "github.com/canstand/compost"
defaultContentLanguage = "en"
title = "Compost"
enableEmoji = true
enableRobotsTXT = true
paginate = 5

# required
[build]
  _merge = 'deep'

# required
[markup]
  _merge = 'deep'

# for better seo
[minify]
  _merge = 'deep'

[module]
[[module.mounts]]
  source = 'assets'
  target = 'assets'
[[module.mounts]]
  source = "hugo_stats.json"
  target = "assets/watching/hugo_stats.json"

[languages]
[languages.en]
  weight = 1
[languages.zh]
  weight = 2
  languageName = '简体中文'
  hasCJKLanguage = true
[[languages.zh.menu.main]]
  name = "首页"
  pageRef = "/"
  weight = 1
[[languages.zh.menu.main]]
  name = "文章"
  pageRef = "posts"
  title = "文章列表"
  weight = 10
[[languages.zh.menu.main]]
  name = "标签"
  pageRef = "tags"
  title = "标签列表"
  weight = 20
[[languages.zh.menu.main]]
  name = "GitHub"
  url = "https://github.com/canstand/compost"
  weight = 30
[languages.zh.params.article]
  dateFormat = "2006/01/02"
  showDraftLabel = true



[author]
  name = "Compost"
  image = "img/author.jpg"
  links = [
    { twitter = "https://twitter.com/" },
    { facebook = "https://facebook.com/" },
    { linkedin = "https://linkedin.com/" },
    { youtube = "https://youtube.com/" },
  ]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  colorScheme = "auto"

[params.homepage]
  showRecent = true

[params.article]
  showBreadcrumbs = true
  showEdit = true
  editURL = "https://github.com/canstand/compost/tree/main/exampleSite/content/"
  editAppendPath = true

[[menu.main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[menu.main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/canstand/compost"
  weight = 30
